### ISSUE TITLE
Show opening hours

### ISSUE THREAD

**Issue by johnjohndoe** [momolinus/atm-map#5]
It would be really helpful when you can show the **opening hours** of the banks. Even nicer would be to **only** show banks which are open at a **certain time** frame as defined by the user. I implemented a similar function for http://briefkastenkarte.de - the [pull request](https://github.com/dbretschneider/briefkastenkarte.de/pull/7) is still pending. Please note there is [ypid/opening_hours.js](https://github.com/ypid/opening_hours.js) which might be a base for the functionality.

**Comment by momolinus** [comment]
map shows now opening hours in a simple kind

**Comment by johnjohndoe** [comment]
Nice work. This is very useful.
