### ISSUE TITLE
Indicate missing opening hours

### ISSUE THREAD

**Issue by johnjohndoe** [momolinus/atm-map#8]
It would be nice if the user could see quickly **where opening hours are missing** without clicking on each icon.
### Current ATM icons

![Current ATM icons](https://cloud.githubusercontent.com/assets/144518/19494956/b1889a68-9581-11e6-8372-77d0ab605ead.png)
### ATMs icons indicating missing opening hours

This could be symbolized by a slightly different icon. As an example I changed the **border color** to yellow as one possibility. Another color might even fit better.

![ATMs icons indicating missing opening hours](https://cloud.githubusercontent.com/assets/144518/19494961/b483e0ec-9581-11e6-9a1f-a5d2cf649397.png)

**Comment by momolinus** [comment]
Rejected because the amount of information presented should be small
